export const SET_ADDSHOW_TRUE = 'DETAIL/SET_ADDSHOW_TRUE';
export const SET_BUYSHOW_TRUE = 'DETAIL/SET_BUYSHOW_TRUE';
export const SET_ADDSHOW_FALSE = 'DETAIL/SET_ADDSHOW_FALSE';
export const SET_BUYSHOW_FALSE = 'DETAIL/SET_BUYSHOW_FALSE';